#!/bin/bash

# Set this to your neorv32 repo path
BASE="../../../neorv32"

# image_gen says it takes ELF but really seems to need raw bin? so convert.
rust-objcopy $1 -O binary "$1.bin"

# Convert bin to fpga bootloader bin format neorv32 expects
"$BASE/sw/image_gen/image_gen" -i "$1.bin" -o "$1-fpga" -t app_bin

# Make it easier to find binary in picocom by cd'ing to the correct folder it's in
cd -- "$(dirname -- "$1")"

# Connect to bootloader over serial using picocom
sudo picocom /dev/ttyUSB0 -b 19200 --imap lfcrlf --omap crlf --send-cmd="ascii-xfr -s -n"
